WebAppexam_DeidreSenra/RegistrationSystem/Controllers/CollegeController.cs
using CollegeManagementSystem.Models;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data.SqlClient;
using System.Web.Mvc;

namespace CollegeManagementSystem.Controllers
{
    public class CollegeController : Controller
    {
        // GET: College
        public ActionResult Index()
        {
            List<Student> students = GetStudents();

            return View("Students", students);
        }

        // GET: College/Details/5
        public ActionResult Details(string id)
        {
            Student student = GetStudent(id);
            return View(student);
        }

        // GET: College/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: College/Create
        [HttpPost]
        public ActionResult Create(Student student)
        {
            if(string.IsNullOrEmpty(student.Country) || string.IsNullOrEmpty(student.EmailAddr)  || string.IsNullOrEmpty(student.LastName)|| string.IsNullOrEmpty(student.FirstName))
            {
                student.ErrorMsg = "Please review the information and try again";
                return View("Create", student);
            }


            try
            {

                SqlConnection cn = new SqlConnection();
                cn.ConnectionString = ConfigurationManager.ConnectionStrings["CollegeManagementSystem"].ConnectionString;
                string query = @"INSERT INTO [dbo].[Students]
                               ([FirstName]
                               ,[LastName]
                               ,[BirthDate]
                               ,[EmailAddr]
                               ,[Country])
                                    VALUES
                               (@firstName,@lastName,@birthDate,@emailAddr,@country)";
                SqlCommand myCommand = new SqlCommand();
                myCommand.Connection = cn;
                myCommand.CommandText = query;
                myCommand.Parameters.AddWithValue("@firstName", student.FirstName);
                myCommand.Parameters.AddWithValue("@lastName", student.LastName);
                myCommand.Parameters.AddWithValue("@birthDate", student.BirthDate);
                myCommand.Parameters.AddWithValue("@emailAddr", student.EmailAddr);
                myCommand.Parameters.AddWithValue("@country", student.Country);

                cn.Open();
                var id = myCommand.ExecuteNonQuery();
                cn.Close();
                return View("Details", student);
            }
            catch (Exception ex)
            {
                //Do something to handle the exception
                return View("Details", student);
            }

        }

        // GET: College/Edit/5
        public ActionResult Edit(string id)
        {
            Student student = GetStudent(id);
            return View(student);
        }

        // POST: College/Edit/5
        [HttpPost]
        public ActionResult Edit(string id, Student student)
        {
            try
            {
                SqlConnection cn = new SqlConnection();
                cn.ConnectionString = ConfigurationManager.ConnectionStrings["CollegeManagementSystem"].ConnectionString;
                string query = @"UPDATE [dbo].[Students]
                                   SET [FirstName] = @firstName
                                      ,[LastName] = @lastName
                                      ,[BirthDate] = @birthDate
                                      ,[EmailAddr] =@emailAddr
                                      ,[Country] = @country
                                 WHERE StudentId = @studentId";
                SqlCommand myCommand = new SqlCommand();
                myCommand.Connection = cn;
                myCommand.CommandText = query;
                myCommand.Parameters.AddWithValue("@firstName", student.FirstName);
                myCommand.Parameters.AddWithValue("@lastName", student.LastName);
                myCommand.Parameters.AddWithValue("@birthDate", student.BirthDate);
                myCommand.Parameters.AddWithValue("@emailAddr", student.EmailAddr);
                myCommand.Parameters.AddWithValue("@country", student.Country);
                myCommand.Parameters.AddWithValue("@studentId", id);

                cn.Open();
                myCommand.ExecuteNonQuery();
                cn.Close();
                return View("Details", student);
            }
            catch (Exception ex)
            {
                //Do something to handle the exception
                return View("Details", student);
            }

        }

        // GET: College/Delete/5
        public ActionResult Delete(string id)
        {
            Student student = GetStudent(id);
            return View(student);
        }

        // POST: College/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                SqlConnection cn = new SqlConnection();
                cn.ConnectionString = ConfigurationManager.ConnectionStrings["CollegeManagementSystem"].ConnectionString;
                string query = @"
                                DELETE FROM [dbo].[Students]
                                    where  StudentId = @studentId";
                SqlCommand myCommand = new SqlCommand();
                myCommand.Connection = cn;
                myCommand.CommandText = query;
                myCommand.Parameters.AddWithValue("@studentId", id);
                cn.Open();
                myCommand.ExecuteNonQuery();
                cn.Close();
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                //Do something to handle the exception
                return RedirectToAction("Index");
            }
        
        }


        private List<Student> GetStudents()
        {
            List<Student> students = new List<Student>();
            SqlConnection myConnection = new SqlConnection();
            myConnection.ConnectionString = ConfigurationManager.ConnectionStrings["CollegeManagementSystem"].ConnectionString;
            try
            {
                myConnection.Open();
                string query = @"
                                SELECT [StudentId]
                                      ,[FirstName]
                                      ,[LastName]
                                      ,[BirthDate]
                                      ,[EmailAddr]
                                      ,[Country]
                                  FROM [CollegeDavid].[dbo].[Students]";


                SqlCommand myCommand = new SqlCommand
                {
                    Connection = myConnection,
                    CommandText = query
                };


                SqlDataReader myReader = myCommand.ExecuteReader();

                while (myReader.Read())
                {
                    Student student = new Student()
                    {
                        BirthDate = Convert.ToDateTime(myReader["BirthDate"]),
                        Country = myReader["Country"].ToString(),
                        EmailAddr = myReader["EmailAddr"].ToString(),
                        FirstName = myReader["FirstName"].ToString(),
                        LastName = myReader["LastName"].ToString(),
                        StudentId = myReader["StudentId"].ToString()

                    };
                    students.Add(student);
                }

            }
            catch (Exception ex)
            {

            }
            finally
            {
                myConnection.Close();
            }

            return students;
        }

        private Student GetStudent(string id)
        {
            SqlConnection myConnection = new SqlConnection();
            myConnection.ConnectionString = ConfigurationManager.ConnectionStrings["CollegeManagementSystem"].ConnectionString;
            try
            {
                myConnection.Open();
                string query = @"
                                SELECT [StudentId]
                                      ,[FirstName]
                                      ,[LastName]
                                      ,[BirthDate]
                                      ,[EmailAddr]
                                      ,[Country]
                                  FROM [CollegeDavid].[dbo].[Students]
                                       Where StudentId=@studentId";


                SqlCommand myCommand = new SqlCommand
                {
                    Connection = myConnection,
                    CommandText = query,

                };
                myCommand.Parameters.AddWithValue("@studentId", id);

                SqlDataReader myReader = myCommand.ExecuteReader();

                while (myReader.Read())
                {
                    Student student = new Student()
                    {
                        BirthDate = Convert.ToDateTime(myReader["BirthDate"]),
                        Country = myReader["Country"].ToString(),
                        EmailAddr = myReader["EmailAddr"].ToString(),
                        FirstName = myReader["FirstName"].ToString(),
                        LastName = myReader["LastName"].ToString(),
                        StudentId = myReader["StudentId"].ToString()

                    };
                    return student;
                }

            }
            catch (Exception ex)
            {

            }
            finally
            {
                myConnection.Close();
            }

            return null;
        }
    }
}

WebAppexam_DeidreSenra/RegistrationSystem/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Bootstrap Example</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
    <style>
        /* Set black background color, white text and some padding */
        footer {
            background-color: #a03796;
            color: white;
            padding: 15px;
        }
    </style>        
</head>
<body>

    <nav class="navbar navbar-inverse">
        <div class="container-fluid">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a href="~/">
                    <img src="~/Content/Images/lift.jpg" height="50">
                </a>
            </div>
            <div class="collapse navbar-collapse" id="myNavbar">
                <ul class="nav navbar-nav">
                    <li class="active"><a href="#">Registration System</a></li>
                    <li><a href="~/">Exit</></a></li>
                    <li>@Html.ActionLink("Create new student", "Create", "College")</li>
                    
                </ul>
                 <ul class="nav navbar-nav navbar-right">
                    <li><a href="~/"><span class="glyphicon glyphicon-user"></span> Login</a></li>
                </ul>
            </div>
        </div>
    </nav>

    <div class="container text-center">
        <div class="row">

              @RenderBody()

        </div>
    </div>






    <footer class="container-fluid text-center">
            <div class="row hide_desktop space80"></div>
            <div class="row  space80"></div>
            <div class="row  space80">
            </div>
            <div class="banner_image">

                <!-- BANNER -->
                <section class="banner black_bg no_padding_bottom">
                    <div class="container">

                        <!-- ROW -->
                        <div class="row first last">

                            <div class="span12 cols centered text_center first last">

                                <h1 class="threeem">Contact</h1>

                            </div>

                        </div>
                        <!--// ROW -->

                    </div>
                </section>
                <!--// BANNER -->

            </div>
            <div class="row  space80">
            </div>
            <div class="row  ">
                <div class="row  ">
                    <div class="full">
                        <div class="col-md-12">
                            <div class="container">
                                <div class="col-md-6">


                                    <div class="tweet">

                                        <div class="white">The office is located in Toronto, ON</div>
                                        <div class="white">Young Street</div>
                                        <div class="white">10th floor</div>

                                        <i class="fa fa-twitter">
                                            <img src="http://www.jjservicios.com.co/index/images/earth.png" alt="Location" class="transparent">
                                        </i>
                                    </div>
                                    <br>
                                    <div class="tweet">

                                        <div class="white">Monday to Frieday 9 am to 6pm</div>
                                        <div class="white">Saturday de 8:30 am to 12:30 pm</div>

                                        <i class="fa fa-twitter">
                                            <img src="http://www.jjservicios.com.co/index/images/time.png" alt="Location" class="transparent">
                                        </i>
                                    </div>
                                </div>
                                <br>
                                <div class="col-md-6">




                                    <div class="tweet">

                                        <div class="white">123456789</div>
                                        <div class="white">(1) 1234567</div>

                                        <i class="fa fa-twitter">
                                            <img src="http://www.campings.net/images/ico-telefono.png" alt="http://www.campings.net/images/ico-telefono.png" class="transparent">
                                        </i>
                                    </div>

                                    <div class="tweet">

                                        <div class="white" style="margin-top: 3px; padding-top: 9px;">
                                            <a href="mailto:contacto@jjservicios.com.co">contact@abcd.com.ca</a>
                                        </div>


                                        <i class="fa fa-twitter">
                                            <img width="50" height="50" src="http://camda.com.mx/wp-content/uploads/2014/06/correo-camda-3.png" style="-webkit-user-select: none; cursor: zoom-in;">
                                        </i>
                                    </div>
                                </div>

                            </div>

                            <div class="row space10"></div>
                            <div class="row">
                            </div>

                            <div class=" space80"></div>
                        </div>
                    </div>
                    <div class=" hide_mobile space80"></div>
                    <div class="hide_mobile space80"></div>
                </div>
            </div>

    </footer>



</body>
</html>